tests: workaround gcc -Wmaybe-uninitialized bug
Workaround the following gcc 11.1.1 -Wmaybe-uninitialized regression:

ioctl_sock_gifconf.c: In function 'gifconf_ioctl':
ioctl_sock_gifconf.c:39:20: error: 'in_len' may be used uninitialized in this function [-Werror=maybe-uninitialized]

* tests/ioctl_sock_gifconf.c: Constify everything to appease gcc.