s390: fix infmname printing check
As it is a EBCDIC string, it is supposed to be checked
with IS_ARRAY_ZERO, similarly to other EBCDIC strings.
Also, it induces a warning with GCC 12:

    s390.c: In function 'print_sthyi_machine':
    s390.c:565:30: error: the comparison will always evaluate as 'true' for the
    address of 'infmname' will never be NULL [-Werror=address]
      565 |                 if (name_val || hdr->infmname) {
          |                              ^~
    s390.c:119:18: note: 'infmname' declared here
      119 |         char     infmname[8];  /**< EBCDIC Machine Name */
          |                  ^~~~~~~~

* src/s390.c (print_sthyi_machine): Use IS_ARRAY_ZERO for hdr->infmname
non-emptiness check.

Fixes: v4.21~73 "Introduce s390_sthyi system call decoder"
Reported-by: Dmitry V. Levin <ldv@strace.io>