print_utils.h: initialize `hex_chars` as an array, not via string
`gcc-15` added a new warning in https://gcc.gnu.org/PR115185:

    print_utils.h:16:35: error: initializer-string for array of 'char' is too long [-Werror=unterminated-string-initialization]
       16 | static const char hex_chars[16] = "0123456789abcdef";
          |                                   ^~~~~~~~~~~~~~~~~~

`strace` does not need to store '\0'. We could either initialize the
arrays with individual bytes or allocate extra byte for null.

This change initializes the array bytewise.