travis: switch from Trusty to Bionic
Ideally, all builds have to be switched, but coverage build,
unfortunately, errors out by Travis CI with a build timeout,
musl-gcc x86 build fails with
"undefined reference to `__stack_chk_fail_local'" error, and gcc-8 arm64
builds error out because of missing gcc-8-multilib-arm-linux-gnueabihf
package.

* .travis.yml (dist): Change to bionic.
(matrix): Add "dist: trusty" to coverage, musl-gcc x86, and gcc-8 arm64
builds.