tests: disable -Werror for useless warnings generated by gcc-15
Apparently, gcc-15 started to generate tons of useless warnings, some of
them are also false positives.  For example, the warnings generated by
-Wstringop-overflow are false positives, and the warnings generated by
-Wunterminated-string-initialization are just useless:

  msg_control.c: In function ‘test_sol_socket’:
  msg_control.c:662:38: error: initializer-string for array of ‘char’ is too long [-Werror=unterminated-string-initialization]
    662 |         static const char text[16] = "0123456789abcdef";
        |                                      ^~~~~~~~~~~~~~~~~~
  msg_control.c: In function ‘main’:
  msg_control.c:380:9: error: writing 16 bytes into a region of size 4 [-Werror=stringop-overflow=]
    380 |         memcpy(CMSG_DATA(cmsg), &tv, sizeof(tv));
        |         ^
  In file included from /usr/include/sys/socket.h:33,
                   from msg_control.c:18:
  /usr/include/bits/socket.h:290:9: note: destination object ‘cmsg_level’ of size 4
    290 |     int cmsg_level;             /* Originating protocol.  */
        |         ^~~~~~~~~~
  msg_control.c:427:9: error: writing 16 bytes into a region of size 4 [-Werror=stringop-overflow=]
    427 |         memcpy(CMSG_DATA(cmsg), &ts, sizeof(ts));
        |         ^
  /usr/include/bits/socket.h:290:9: note: destination object ‘cmsg_level’ of size 4
    290 |     int cmsg_level;             /* Originating protocol.  */
        |         ^~~~~~~~~~
  net-sockaddr.c: In function ‘check_ipx’:
  net-sockaddr.c:286:30: error: initializer-string for array of ‘unsigned char’ is too long [-Werror=unterminated-string-initialization]
    286 |                 .sipx_node = "ABCDEF",
        |                              ^~~~~~~~
  net-sockaddr.c: In function ‘check_x25’:
  net-sockaddr.c:464:32: error: initializer-string for array of ‘char’ is too long [-Werror=unterminated-string-initialization]
    464 |                 .sx25_addr = { "0123456789abcdef" },
        |                                ^~~~~~~~~~~~~~~~~~
  net-sockaddr.c: In function ‘check_ll’:
  net-sockaddr.c:547:29: error: initializer-string for array of ‘unsigned char’ is too long [-Werror=unterminated-string-initialization]
    547 |                 .sll_addr = "abcdefgh"
        |                             ^~~~~~~~~~
  net-sockaddr.c: In function ‘check_sco’:
  net-sockaddr.c:638:33: error: initializer-string for array of ‘unsigned char’ is too long [-Werror=unterminated-string-initialization]
    638 |                 .sco_bdaddr.b = "abcdef"
        |                                 ^~~~~~~~
  net-sockaddr.c: In function ‘check_rc’:
  net-sockaddr.c:658:32: error: initializer-string for array of ‘unsigned char’ is too long [-Werror=unterminated-string-initialization]
    658 |                 .rc_bdaddr.b = "abcdef",
        |                                ^~~~~~~~
  net-sockaddr.c: In function ‘check_l2’:
  net-sockaddr.c:682:32: error: initializer-string for array of ‘unsigned char’ is too long [-Werror=unterminated-string-initialization]
    682 |                 .l2_bdaddr.b = "abcdef",
        |                                ^~~~~~~~
  netlink_protocol.c: In function ‘send_query’:
  netlink_protocol.c:39:26: error: initializer-string for array of ‘char’ is too long [-Werror=unterminated-string-initialization]
     39 |                 .magic = "abcd"
        |                          ^~~~~~
  nlattr_ifla_port.c: In function ‘main’:
  nlattr_ifla_port.c:40:32: error: initializer-string for array of ‘unsigned char’ is too long [-Werror=unterminated-string-initialization]
     40 |                 .vsi_type_id = "abc",
        |                                ^~~~~
  nlattr_ndmsg.c: In function ‘main’:
  nlattr_ndmsg.c:123:39: error: initializer-string for array of ‘unsigned char’ is too long [-Werror=unterminated-string-initialization]
    123 |         static const uint8_t mac[6] = "\xf8\xc2\x49\x13\x57\xbd";
        |                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~
  nlattr_inet_diag_msg.c:170:13: error: initializer-string for array of ‘unsigned char’ is too long [-Werror=unterminated-string-initialization]
    170 |             "OH HAI THAR\0\1\2\3\4\5\6\7\3779876543210abcdefghijklmnopqrstuv"
        |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  pread64-pwrite64.c: In function ‘dump_str’:
  pread64-pwrite64.c:21:38: error: initializer-string for array of ‘char’ is too long [-Werror=unterminated-string-initialization]
     21 |         static const char dots[16] = "................";
        |                                      ^~~~~~~~~~~~~~~~~~
  recv-MSG_TRUNC.c: In function ‘main’:
  recv-MSG_TRUNC.c:34:37: error: initializer-string for array of ‘char’ is too long [-Werror=unterminated-string-initialization]
     34 |         static const char sbuf[2] = "AB";
        |                                     ^~~~
  read-write.c: In function ‘dump_str_ex’:
  read-write.c:23:17: error: initializer-string for array of ‘char’ is too long [-Werror=unterminated-string-initialization]
     23 |                 "................................"
        |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  recvfrom-MSG_TRUNC.c: In function ‘main’:
  recvfrom-MSG_TRUNC.c:17:37: error: initializer-string for array of ‘char’ is too long [-Werror=unterminated-string-initialization]
     17 |         static const char sbuf[2] = "AB";
        |                                     ^~~~
  sockaddr_xlat.c: In function ‘check_ll’:
  sockaddr_xlat.c:199:29: error: initializer-string for array of ‘unsigned char’ is too long [-Werror=unterminated-string-initialization]
    199 |                 .sll_addr = "abcdefgh"
        |                             ^~~~~~~~~~
  sockaddr_xlat.c: In function ‘check_sco’:
  sockaddr_xlat.c:349:33: error: initializer-string for array of ‘unsigned char’ is too long [-Werror=unterminated-string-initialization]
    349 |                 .sco_bdaddr.b = "abcdef"
        |                                 ^~~~~~~~
  sockaddr_xlat.c: In function ‘check_rc’:
  sockaddr_xlat.c:387:32: error: initializer-string for array of ‘unsigned char’ is too long [-Werror=unterminated-string-initialization]
    387 |                 .rc_bdaddr.b = "abcdef",
        |                                ^~~~~~~~
  sockaddr_xlat.c: In function ‘check_rxrpc’:
  sockaddr_xlat.c:507:49: error: initializer-string for array of ‘unsigned char’ is too long [-Werror=unterminated-string-initialization]
    507 |                                    { .s6_addr = "OH HAI THAR!\0\0\0\xf" } } } },
        |                                                 ^~~~~~~~~~~~~~~~~~~~~~~
  sockaddr_xlat.c:519:49: error: initializer-string for array of ‘unsigned char’ is too long [-Werror=unterminated-string-initialization]
    519 |                                    { .s6_addr = "OH HAI THAR!\0\0\0\xf" } } } },
        |                                                 ^~~~~~~~~~~~~~~~~~~~~~~
  sockaddr_xlat.c: In function ‘check_ieee802154’:
  sockaddr_xlat.c:626:33: error: initializer-string for array of ‘unsigned char’ is too long [-Werror=unterminated-string-initialization]
    626 |                     { .hwaddr = "\xf8\xf9\xfa\xfb\xfc\xfd\xfe\xff" } } },
        |                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  sockaddr_xlat.c: In function ‘check_alg’:
  sockaddr_xlat.c:736:42: error: initializer-string for array of ‘unsigned char’ is too long [-Werror=unterminated-string-initialization]
    736 |                 { { AF_ALG, .salg_type = "OH HAI\1\n\377\\\"\0\t\v",
        |                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~

Since nobody is going to waste their time before the release by
silencing new useless warnings in the code, disable -Werror
for these warnings until gcc is fixed.

* m4/st_warn_cflags.m4 (st_WARN_CFLAGS): Add
-Wno-error=unterminated-string-initialization and
-Wno-error=stringop-overflow to TEST_WARN_CFLAGS.
* m4/mpers.m4 (st_MPERS): Wrap TEST_WARN_CFLAGS using pushdef/popdef.
* m4/ax_prog_cc_for_build.m4 (AC_PROG_CC_FOR_BUILD): Likewise.
* tests/Makefile.am (AM_CFLAGS): $(TEST_WARN_CFLAGS).