sched_attr: Define conditionally on SCHED_ATTR_SIZE_VER1
glibc 2.41+ has added [1] definitions for sched_setattr and
sched_getattr functions and struct sched_attr.  Therefore, it needs
to be checked for here as well before defining struct sched_attr.

Fixes builds with glibc/trunk.

In file included from ../../strace-6.11/src/sched.c:14:
../../strace-6.11/src/sched_attr.h:16:8: error: redefinition of 'sched_attr'
   16 | struct sched_attr {
      |        ^
/usr/include/linux/sched/types.h:98:8: note: previous definition is here
   98 | struct sched_attr {
      |        ^

[1] https://sourceware.org/git/?p=glibc.git;a=commitdiff;h=21571ca0d70302909cf72707b2a7736cf12190a0
Signed-off-by: Khem Raj <raj.khem@gmail.com>