tests: fix build on aarch64
This fixes the following compilation errors on aarch64

  In file included from ptrace-Xraw.c:2:
  ptrace.c: In function 'check_compat_ptrace_req':
  ptrace.c:1662:28: error: expected expression before ',' token
   1662 |                req, NRAW(s), pid, errstr);
        |                            ^
  ptrace.c:1667:28: error: expected expression before ',' token
   1667 |                req, NRAW(s), pid, errstr);
        |                            ^

* tests/ptrace.c [__arm64__ || __aarch64__] (check_compat_ptrace_req):
Update to new NRAW semantics by switching to use XLAT_RAW instead.

Fixes: v5.19-4-g10eba44ca "tests: make {,N}{ABBR,RAW,VERB} macros more versatile"