util: add offs sanity check to print_clock_t
While it is not strictly needed right now, the code that uses
the calculated offs value lacks any checks for possible buf overruns,
which is not defensive enough, so let's add them.  Reported by covscan:

    Error: OVERRUN (CWE-119):
    strace-5.18/src/util.c:248: assignment: Assigning:
    "offs" = "ilog10(val / clk_tck)". The value of "offs" is now between
    16 and 31 (inclusive).
    strace-5.18/src/util.c:249: overrun-local: Overrunning array of 30 bytes
    at byte offset 31 by dereferencing pointer "buf + offs". [Note: The source
    code implementation of the function has been overridden by a builtin model.]

    Error: OVERRUN (CWE-119):
    strace-5.18/src/util.c:248: assignment: Assigning:
    "offs" = "ilog10(val / clk_tck)". The value of "offs" is now between
    16 and 31 (inclusive).
    strace-5.18/src/util.c:253: overrun-buffer-arg: Overrunning array "buf"
    of 30 bytes by passing it to a function which accesses it at byte offset
    32 using argument "offs + 2UL" (which evaluates to 33). [Note: The source
    code implementation of the function has been overridden by a builtin model.]

    Error: OVERRUN (CWE-119):
    strace-5.18/src/util.c:248: assignment: Assigning:
    "offs" = "ilog10(val / clk_tck)". The value of "offs" is now between
    16 and 31 (inclusive).
    strace-5.18/src/util.c:254: overrun-local: Overrunning array "buf"
    of 30 bytes at byte offset 32 using index "offs + 1UL" (which evaluates
    to 32).

* src/util.c (print_clock_t): Add check that offs is small enough
for it and "offs + 2" not to overrun buf.