time: Protect the print_timezone() function
To avoid the following error:
time.c:17:1: error: 'print_timezone' defined but not used [-Werror=unused-function]

ensure that print_timezone is only defined if we are going to use it.

Signed-off-by: Alistair Francis <alistair.francis@wdc.com>

* time.c (print_timezone): Place under
[HAVE_ARCH_TIME32_SYSCALLS || HAVE_ARCH_OLD_TIME64_SYSCALLS] guard.

Complements: v5.6~28 "linux/32: move wait4 and [gs]ettimeofday from syscallent.h to syscallent-time32.h"
Co-authored-by: Dmitry V. Levin <ldv@altlinux.org>