mmsghdr: workaround -Warray-bounds regression in Red Hat gcc
The version of gcc packaged into Rawhide erroneously produces
the following false positive diagnostics:

mmsghdr.c: In function 'do_recvmmsg':
mmsghdr.c:87:23: error: array subscript 'struct mmsgvec_data[0]' is partly outside array bounds of 'unsigned char[4108]' [-Werror=array-bounds]
   87 |         data->timeout = xstrdup(timeout);
      |         ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~

Tested with:
$ gcc --version |head -1
gcc (GCC) 11.0.0 20201204 (Red Hat 11.0.0-0)

* mmsghdr.c (struct mmsgvec_data): Change namelen[IOV_MAX] to an array
of zero length.