defs.h: fix build with uClibc
Commit ee5459531280f ("open: refactor sprint_open_modes64 to support
multiple xlat tables") added a reference to va_list, but did not add the
required header. This breaks build with uClibc:

In file included from bjm.c:12:
defs.h:1060:53: error: unknown type name ‘va_list’
 1060 |                                    enum xlat_style, va_list xlats);
      |                                                     ^~~~~~~

Include stdarg.h to fix the build.