src/xlat: remove remnants of unnecessary idx usage in xlookup
As there is no idx saving between calls anymore, there's no need to use
(and update) idx in the XT_SORTED case.  Reported by clang as a dead store:

    Error: CLANG_WARNING:
    strace-5.18/src/xlat.c:84:4: warning[deadcode.DeadStores]: Value stored to 'idx' is never read

* src/xlat.c (xlookup): Remove idx declaration;  declare idx inside
of the for loop in the XT_NORMAL case; do not offset x->data and x->size
by offs in the XT_SORTED case and do not update idx upon successful
lookup.

Complements: v5.15~164 "xlat: no longer interpret NULL xlat as continuation"