tests/s390_sthyi.c: make utility functions inline
When built with --enable-gcc-Werror, s390_sthyi test build fails
with the following error:

	s390_sthyi.c:63:1: error: ‘print_u8’ defined but not used [-Werror=unused-function]
	 print_u8(const char *prefix, unsigned char *buf, unsigned int offs, bool zero)
	 ^~~~~~~~

Apparently, after some back and forth, all occurrences of printing u8
values landed under verbose printing, so this function is no longer
used in non-verbose mode.  Let's avoid this in the future by inlining
all the utility functions in this test.

* tests/s390_sthyi.c (print_0x8, print_u8, print_u16, print_x32,
print_weight, ebcdic2ascii, is_empty, print_ebcdic): Add inline
qualifier.
[!VERBOSE] (is_empty): Remove "# if VERBOSE" guard.