auxstr: show namespaces when -e namespace=new is given
    $ src/strace -qq -e signal=none -e unshare -e namespace=new unshare --user --net /bin/true
    unshare(CLONE_NEWUSER|CLONE_NEWNET)     = 0 (net:[4026537408], user:[4026537407])
    $ src/strace -qq -f -e signal=none -e unshare,clone -e namespace=new \
      		 podman run --rm -ti registry.access.redhat.com/ubi7/ubi:latest /bin/true
    [pid 1089104] clone(child_stack=NULL, flags=CLONE_NEWNS|CLONE_NEWUSER|SIGCHLD) = 1089110 (mnt:[4026531841], user:[4026531837])
    [pid 1089104] clone(child_stack=NULL, flags=CLONE_VM|CLONE_VFORK|SIGCHLD) = 1089111
    ERRO[0000] running `/usr/bin/newuidmap 1089110 0 1000 1 1 100000 65536`: newuidmap: write to uid_map failed: Operation not permitted
    Error: cannot set up namespace using "/usr/bin/newuidmap": exit status 1

* src/clone.c: Include "xstring.h" and <unistd.h>.
(show_namespace): New variable.
(namespace_auxstr_init, read_namespace_id, get_namespace_auxstr): New
functions.
(SYS_FUNC(clone)): Don't add RVAL_DECODED to the return
value if the clone makes new namespaces (entering).
Set the value returned from get_namespace_auxstr() to the auxstr
member of tcp if the clone makes new namespaces, and add RVAL_STR to
the return value (leaving).
(SYS_FUNC(clone3), SYS_FUNC(setns), SYS_FUNC(unshare)): Likewise.
* src/defs.h (qualify_namespace, namespace_auxstr_init): New
declaration.
* src/filter_qualify.c (qualify_namespace): New function.
(qual_options): Add "namespace".
* src/strace.c (usage): Describe -e namespace=new option.
(init) <namespace_qual>: New constant.
(init) <GETOPT_QUAL_NAMESPACE>: New enumerator.
(init) <longopts>: Add "namespace".
(init): Call qualify_namespace when --namespace is specified.
* doc/strace1.n (-e namespace=new): Document the option.

Changes in v2 (Suggested by Dmitry V. Levin <ldv@strace.io>):
* Consider CLONE_INTO_CGROUP flag, and
* Use an array instead of a sequence of if-statements in
  get_namespace_auxstr(),
* Remove unnecessary cast operations,
* Translate pids with translate_pid() before passing them
  to get_namespace_auxstr.

Changes in v4 (Suggested by Dmitry V. Levin <ldv@strace.io>):
* Use syserror() instead of comparing tcp->u_rval with 0,
* Fix the style of conditional expressions.

Changes in v5 (Suggested by Dmitry V. Levin <ldv@strace.io>):
* Move the NEWS entry,
* Update the formatting of the man page,
* Don't cast tcp->u_rval to int when calling get_namespace_auxstr.

Signed-off-by: Masatake YAMATO <yamato@redhat.com>